package Project;

import java.awt.GridLayout;
import java.sql.Connection;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class SejongCampingGUI extends JFrame {

	JButton btnReset, btnManager, btnUser;
	// manager
	JButton CROinsert, CROdelete, CROupdate;
	JButton Cinsert, Cdelete, Cupdate;
	JButton CUSTinsert, CUSTdelete, CUSTupdate;
	JButton CRinsert, CRdelete, CRupdate;
	JButton Creturn;
	JButton CRIinsert, CRIdelete, CRIupdate;
	JButton Select1, Select2, Select3, Select4;

	JLabel CRO, OI, ON, OA, OP, MN, ME;
	JLabel CC, CCI, CCN, CCCN, CCP, CCIM, CCDI, CCRC, CCROID, CCD;
	JLabel CUST, CUSTID, CUSTNAME, CUSTADDRESS, CUSTPHONE, CUSTEMAIL;
	JLabel CR, CRID, CRNAME, CRADDRESS, CRPHONE, CRMANAGER, CRMANAGEREMAIL;
	JLabel CRETURN, CRETURNID, CRETURNREPAIR;
	JLabel CRINFO, CRNUM, CCARID, CREPAIRID, CROID, CUSTOMERID, REPAIRDETAIL, REPAIRDATE, REPAIRCOST, RETURNDATE,
			OTHERREPAIRINFO;
	JLabel S11, S12, S13, S14, S15;
	JLabel S21, S22, S23, S24, S25;
	JLabel S31, S32, S33, S34, S35;
	JLabel S41, S42, S43, S44, S45;

	static JTextField OITF, ONTF, OATF, OPTF, MNTF, METF;
	static JTextField CCITF, CCNTF, CCCNTF, CCPTF, CCIMTF, CCDITF, CCRCTF, CCROIDTF, CCDTF;
	static JTextField CUSTIDTF, CUSTNAMETF, CUSTADDRESSTF, CUSTPHONETF, CUSTEMAILTF;
	static JTextField CRIDTF, CRNAMETF, CRADDRESSTF, CRPHONETF, CRMANAGERTF, CRMANAGEREMAILTF;
	static JTextField CRETURNIDTF, CRETURNREPAIRTF;
	static JTextField CRNUMTF, CCARIDTF, CREPAIRIDTF, CROIDTF, CUSTOMERIDTF, REPAIRDETAILTF, REPAIRDATETF, REPAIRCOSTTF,
			RETURNDATETF, OTHERREPAIRINFOTF;

	// user
	JButton userselect, userrent;

	JLabel uscampingcar, uselect;
	JLabel uscondition, usnum, uscost;
	JLabel urcampingcar, urselection, urrent;
	JLabel urrentid, urcarid, urcustid, urrentdate, urterm;

	static JTextField usnumtf, uscosttf;
	static JTextField urrentidtf, urcaridtf, urcustidtf, urrentdatetf, urtermtf;

	// JTextField
	static JTextArea txtResult;
	JPanel pn1, pn2;

	static Connection con;

	public SejongCampingGUI() {
		super("Jung_CG");
		layInitChoice();
		new DBClass();

		setVisible(true);
		setBounds(200, 200, 500, 500); // 가로위치,세로위치,가로길이,세로길이

		addWindowListener(new JFrameWindowClosingEventHandler());
	}

	public SejongCampingGUI(int i, Connection conn) {
		super("Jung_CG");
		this.con = conn;
		if (i == 1) {
			System.out.println("==================");
			System.out.println("관리자 모드로 로그인합니다.");
			System.out.println("==================");
			layInitManager();
			setVisible(true);
			setBounds(100, 0, 1800, 1000);
		} else if (i == 2) {
			System.out.println("=====================");
			System.out.println("일반 사용자 모드로 로그인합니다.");
			System.out.println("=====================");
			layInitUser();
			setVisible(true);
			setBounds(100, 0, 1800, 1000);
		}

	}

	public void layInitChoice() {
		btnManager = new JButton("관리자 모드");
		btnUser = new JButton("일반 사용자 모드");

		pn2 = new JPanel(new GridLayout(1, 2));
		pn2.add(btnManager);
		pn2.add(btnUser);
		add("Center", pn2);
		btnManager.addActionListener(new DBActionListener());
		btnUser.addActionListener(new DBActionListener());
	}

	public void layInitManager() {
		CRO = new JLabel("캠핑카 대여 회사");
		CRO.setHorizontalAlignment(JLabel.CENTER);
		OI = new JLabel("대여 회사 ID(PK)");
		OI.setHorizontalAlignment(JLabel.CENTER);
		ON = new JLabel("회사명");
		ON.setHorizontalAlignment(JLabel.CENTER);
		OA = new JLabel("주소");
		OA.setHorizontalAlignment(JLabel.CENTER);
		OP = new JLabel("전화번호");
		OP.setHorizontalAlignment(JLabel.CENTER);
		MN = new JLabel("담당자 이름");
		MN.setHorizontalAlignment(JLabel.CENTER);
		ME = new JLabel("담당자 이메일");
		ME.setHorizontalAlignment(JLabel.CENTER);
		CC = new JLabel("캠핑카");
		CC.setHorizontalAlignment(JLabel.CENTER);
		CCI = new JLabel("캠핑카등록ID(PK)");
		CCI.setHorizontalAlignment(JLabel.CENTER);
		CCN = new JLabel("이름");
		CCN.setHorizontalAlignment(JLabel.CENTER);
		CCCN = new JLabel("차량번호");
		CCCN.setHorizontalAlignment(JLabel.CENTER);
		CCP = new JLabel("승차 인원수");
		CCP.setHorizontalAlignment(JLabel.CENTER);
		CCIM = new JLabel("캠핑카 이미지");
		CCIM.setHorizontalAlignment(JLabel.CENTER);
		CCDI = new JLabel("상세 정보");
		CCDI.setHorizontalAlignment(JLabel.CENTER);
		CCRC = new JLabel("대여 비용");
		CCRC.setHorizontalAlignment(JLabel.CENTER);
		CCROID = new JLabel("대여 회사 ID(FK)");
		CCROID.setHorizontalAlignment(JLabel.CENTER);
		CCD = new JLabel("등록 일자");
		CCD.setHorizontalAlignment(JLabel.CENTER);
		CUST = new JLabel("고객");
		CUST.setHorizontalAlignment(JLabel.CENTER);
		CUSTID = new JLabel("운전면허번호(PK)");
		CUSTID.setHorizontalAlignment(JLabel.CENTER);
		CUSTNAME = new JLabel("고객명");
		CUSTNAME.setHorizontalAlignment(JLabel.CENTER);
		CUSTADDRESS = new JLabel("주소");
		CUSTADDRESS.setHorizontalAlignment(JLabel.CENTER);
		CUSTPHONE = new JLabel("전화번호");
		CUSTPHONE.setHorizontalAlignment(JLabel.CENTER);
		CUSTEMAIL = new JLabel("이메일");
		CUSTEMAIL.setHorizontalAlignment(JLabel.CENTER);
		CR = new JLabel("캠핑카 정비소");
		CR.setHorizontalAlignment(JLabel.CENTER);
		CRID = new JLabel("정비소 ID(PK)");
		CRID.setHorizontalAlignment(JLabel.CENTER);
		CRNAME = new JLabel("정비소명");
		CRNAME.setHorizontalAlignment(JLabel.CENTER);
		CRADDRESS = new JLabel("주소");
		CRADDRESS.setHorizontalAlignment(JLabel.CENTER);
		CRPHONE = new JLabel("전화번호");
		CRPHONE.setHorizontalAlignment(JLabel.CENTER);
		CRMANAGER = new JLabel("담당자 이름");
		CRMANAGER.setHorizontalAlignment(JLabel.CENTER);
		CRMANAGEREMAIL = new JLabel("담당자 이메일");
		CRMANAGEREMAIL.setHorizontalAlignment(JLabel.CENTER);
		CRETURN = new JLabel("캠핑카 반환");
		CRETURN.setHorizontalAlignment(JLabel.CENTER);
		CRETURNID = new JLabel("고유 대여 번호(필)");
		CRETURNID.setHorizontalAlignment(JLabel.CENTER);
		CRETURNREPAIR = new JLabel("수리 필요 여부");
		CRETURNREPAIR.setHorizontalAlignment(JLabel.CENTER);
		CRINFO = new JLabel("캠핑카 정비 정보");
		CRINFO.setHorizontalAlignment(JLabel.CENTER);
		CRNUM = new JLabel("고유정비번호(PK)");
		CRNUM.setHorizontalAlignment(JLabel.CENTER);
		CCARID = new JLabel("캠핑카 등록 ID(필)");
		CCARID.setHorizontalAlignment(JLabel.CENTER);
		CREPAIRID = new JLabel("정비소 ID(필)");
		CREPAIRID.setHorizontalAlignment(JLabel.CENTER);
		CROID = new JLabel("대여회사 ID");
		CROID.setHorizontalAlignment(JLabel.CENTER);
		CUSTOMERID = new JLabel("운전면허증 번호");
		CUSTOMERID.setHorizontalAlignment(JLabel.CENTER);
		REPAIRDETAIL = new JLabel("정비 내역");
		REPAIRDETAIL.setHorizontalAlignment(JLabel.CENTER);
		REPAIRDATE = new JLabel("수리날짜");
		REPAIRDATE.setHorizontalAlignment(JLabel.CENTER);
		REPAIRCOST = new JLabel("수리비용");
		REPAIRCOST.setHorizontalAlignment(JLabel.CENTER);
		RETURNDATE = new JLabel("납입기한");
		RETURNDATE.setHorizontalAlignment(JLabel.CENTER);
		OTHERREPAIRINFO = new JLabel("기타정비내역");
		OTHERREPAIRINFO.setHorizontalAlignment(JLabel.CENTER);
		S11 = new JLabel("현재 수리가");
		S11.setHorizontalAlignment(JLabel.CENTER);
		S12 = new JLabel("필요한 차량");
		S12.setHorizontalAlignment(JLabel.CENTER);
		S13 = new JLabel("전체에 대한");
		S13.setHorizontalAlignment(JLabel.CENTER);
		S14 = new JLabel("현재 수리");
		S14.setHorizontalAlignment(JLabel.CENTER);
		S15 = new JLabel("진행 상황");
		S15.setHorizontalAlignment(JLabel.CENTER);
		S21 = new JLabel("현재 차량을");
		S21.setHorizontalAlignment(JLabel.CENTER);
		S22 = new JLabel("렌트 중인");
		S22.setHorizontalAlignment(JLabel.CENTER);
		S23 = new JLabel("고객의 전체 고객");
		S23.setHorizontalAlignment(JLabel.CENTER);
		S24 = new JLabel(" 정보와 해당 ");
		S24.setHorizontalAlignment(JLabel.CENTER);
		S25 = new JLabel("캠핑카 등록번호");
		S25.setHorizontalAlignment(JLabel.CENTER);
		S31 = new JLabel("현재 수리가");
		S31.setHorizontalAlignment(JLabel.CENTER);
		S32 = new JLabel("필요해서 정비");
		S32.setHorizontalAlignment(JLabel.CENTER);
		S33 = new JLabel("중인 차량이 없는");
		S33.setHorizontalAlignment(JLabel.CENTER);
		S34 = new JLabel("캠핑카 정비소의");
		S34.setHorizontalAlignment(JLabel.CENTER);
		S35 = new JLabel("전체 정보");
		S35.setHorizontalAlignment(JLabel.CENTER);
		S41 = new JLabel("현재 수리중인 차");
		S41.setHorizontalAlignment(JLabel.CENTER);
		S42 = new JLabel("량의 대여회사와 ");
		S42.setHorizontalAlignment(JLabel.CENTER);
		S43 = new JLabel("수리를 맡은 ");
		S43.setHorizontalAlignment(JLabel.CENTER);
		S44 = new JLabel("정비소의 ID와");
		S44.setHorizontalAlignment(JLabel.CENTER);
		S45 = new JLabel(" 이름, 주소");
		S45.setHorizontalAlignment(JLabel.CENTER);

		OITF = new JTextField(10);
		ONTF = new JTextField(10);
		OATF = new JTextField(10);
		OPTF = new JTextField(10);
		MNTF = new JTextField(10);
		METF = new JTextField(10);
		CCITF = new JTextField(10);
		CCNTF = new JTextField(10);
		CCCNTF = new JTextField(10);
		CCPTF = new JTextField(10);
		CCIMTF = new JTextField(10);
		CCDITF = new JTextField(10);
		CCRCTF = new JTextField(10);
		CCROIDTF = new JTextField(10);
		CCDTF = new JTextField(10);
		CUSTIDTF = new JTextField(10);
		CUSTNAMETF = new JTextField(10);
		CUSTADDRESSTF = new JTextField(10);
		CUSTPHONETF = new JTextField(10);
		CUSTEMAILTF = new JTextField(10);
		CRIDTF = new JTextField(10);
		CRNAMETF = new JTextField(10);
		CRADDRESSTF = new JTextField(10);
		CRPHONETF = new JTextField(10);
		CRMANAGERTF = new JTextField(10);
		CRMANAGEREMAILTF = new JTextField(10);
		CRETURNIDTF = new JTextField(10);
		CRETURNREPAIRTF = new JTextField(10);
		CRNUMTF = new JTextField(10);
		CCARIDTF = new JTextField(10);
		CREPAIRIDTF = new JTextField(10);
		CROIDTF = new JTextField(10);
		CUSTOMERIDTF = new JTextField(10);
		REPAIRDETAILTF = new JTextField(10);
		REPAIRDATETF = new JTextField(10);
		REPAIRCOSTTF = new JTextField(10);
		RETURNDATETF = new JTextField(10);
		OTHERREPAIRINFOTF = new JTextField(10);

		CROinsert = new JButton("대여회사 입력");
		CROdelete = new JButton("대여회사 삭제");
		CROupdate = new JButton("대여회사 변경");
		Cinsert = new JButton("캠핑카 입력");
		Cdelete = new JButton("캠핑카 삭제");
		Cupdate = new JButton("캠핑카 변경");
		CUSTinsert = new JButton("고객 입력");
		CUSTdelete = new JButton("고객 삭제");
		CUSTupdate = new JButton("고객 변경");
		CRinsert = new JButton("정비소 입력");
		CRdelete = new JButton("정비소 삭제");
		CRupdate = new JButton("정비소 변경");
		Creturn = new JButton("반환");
		CRIinsert = new JButton("정비정보 입력");
		CRIdelete = new JButton("정비정보 삭제");
		CRIupdate = new JButton("정비정보 변경");
		Select1 = new JButton("검색1");
		Select2 = new JButton("검색2");
		Select3 = new JButton("검색3");
		Select4 = new JButton("검색4");
		btnReset = new JButton("초기화");

		txtResult = new JTextArea();

		pn1 = new JPanel(new GridLayout(17, 14));
		pn1.add(btnReset);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(CRO);
		pn1.add(OI);
		pn1.add(ON);
		pn1.add(OA);
		pn1.add(OP);
		pn1.add(MN);
		pn1.add(ME);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(OITF);
		pn1.add(ONTF);
		pn1.add(OATF);
		pn1.add(OPTF);
		pn1.add(MNTF);
		pn1.add(METF);
		pn1.add(CROinsert);
		pn1.add(CROdelete);
		pn1.add(CROupdate);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(CC);
		pn1.add(CCI);
		pn1.add(CCN);
		pn1.add(CCCN);
		pn1.add(CCP);
		pn1.add(CCIM);
		pn1.add(CCDI);
		pn1.add(CCRC);
		pn1.add(CCROID);
		pn1.add(CCD);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(CCITF);
		pn1.add(CCNTF);
		pn1.add(CCCNTF);
		pn1.add(CCPTF);
		pn1.add(CCIMTF);
		pn1.add(CCDITF);
		pn1.add(CCRCTF);
		pn1.add(CCROIDTF);
		pn1.add(CCDTF);
		pn1.add(Cinsert);
		pn1.add(Cdelete);
		pn1.add(Cupdate);
		pn1.add(new JLabel(""));
		pn1.add(CUST);
		pn1.add(CUSTID);
		pn1.add(CUSTNAME);
		pn1.add(CUSTADDRESS);
		pn1.add(CUSTPHONE);
		pn1.add(CUSTEMAIL);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(CUSTIDTF);
		pn1.add(CUSTNAMETF);
		pn1.add(CUSTADDRESSTF);
		pn1.add(CUSTPHONETF);
		pn1.add(CUSTEMAILTF);
		pn1.add(CUSTinsert);
		pn1.add(CUSTdelete);
		pn1.add(CUSTupdate);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(CR);
		pn1.add(CRID);
		pn1.add(CRNAME);
		pn1.add(CRADDRESS);
		pn1.add(CRPHONE);
		pn1.add(CRMANAGER);
		pn1.add(CRMANAGEREMAIL);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(CRIDTF);
		pn1.add(CRNAMETF);
		pn1.add(CRADDRESSTF);
		pn1.add(CRPHONETF);
		pn1.add(CRMANAGERTF);
		pn1.add(CRMANAGEREMAILTF);
		pn1.add(CRinsert);
		pn1.add(CRdelete);
		pn1.add(CRupdate);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(CRETURN);
		pn1.add(CRETURNID);
		pn1.add(CRETURNREPAIR);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(CRETURNIDTF);
		pn1.add(CRETURNREPAIRTF);
		pn1.add(Creturn);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(CRINFO);
		pn1.add(CRNUM);
		pn1.add(CCARID);
		pn1.add(CREPAIRID);
		pn1.add(REPAIRDETAIL);
		pn1.add(REPAIRDATE);
		pn1.add(REPAIRCOST);
		pn1.add(RETURNDATE);
		pn1.add(OTHERREPAIRINFO);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(CRNUMTF);
		pn1.add(CCARIDTF);
		pn1.add(CREPAIRIDTF);
		pn1.add(REPAIRDETAILTF);
		pn1.add(REPAIRDATETF);
		pn1.add(REPAIRCOSTTF);
		pn1.add(RETURNDATETF);
		pn1.add(OTHERREPAIRINFOTF);
		pn1.add(CRIinsert);
		pn1.add(CRIdelete);
		pn1.add(CRIupdate);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(S11);
		pn1.add(S12);
		pn1.add(S13);
		pn1.add(S14);
		pn1.add(S15);
		pn1.add(Select1);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(S21);
		pn1.add(S22);
		pn1.add(S23);
		pn1.add(S24);
		pn1.add(S25);
		pn1.add(Select2);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(S31);
		pn1.add(S32);
		pn1.add(S33);
		pn1.add(S34);
		pn1.add(S35);
		pn1.add(Select3);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(S41);
		pn1.add(S42);
		pn1.add(S43);
		pn1.add(S44);
		pn1.add(S45);
		pn1.add(Select4);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));

		txtResult.setEditable(false);
		JScrollPane scrollPane = new JScrollPane(txtResult);
		add("North", pn1);
		add("Center", scrollPane);
		btnReset.addActionListener(new DBActionListener());
		CROinsert.addActionListener(new DBActionListener());
		CROdelete.addActionListener(new DBActionListener());
		CROupdate.addActionListener(new DBActionListener());
		Cinsert.addActionListener(new DBActionListener());
		Cdelete.addActionListener(new DBActionListener());
		Cupdate.addActionListener(new DBActionListener());
		CUSTinsert.addActionListener(new DBActionListener());
		CUSTdelete.addActionListener(new DBActionListener());
		CUSTupdate.addActionListener(new DBActionListener());
		CRinsert.addActionListener(new DBActionListener());
		CRdelete.addActionListener(new DBActionListener());
		CRupdate.addActionListener(new DBActionListener());
		Creturn.addActionListener(new DBActionListener());
		CRIinsert.addActionListener(new DBActionListener());
		CRIdelete.addActionListener(new DBActionListener());
		CRIupdate.addActionListener(new DBActionListener());
		Select1.addActionListener(new DBActionListener());
		Select2.addActionListener(new DBActionListener());
		Select3.addActionListener(new DBActionListener());
		Select4.addActionListener(new DBActionListener());
	}

	public void layInitUser() {
		userselect = new JButton("검색하기");
		userrent = new JButton("대여하기");

		uscampingcar = new JLabel("캠핑카");
		uscampingcar.setHorizontalAlignment(JLabel.CENTER);
		uselect = new JLabel("검색");
		uselect.setHorizontalAlignment(JLabel.CENTER);
		uscondition = new JLabel("조건");
		uscondition.setHorizontalAlignment(JLabel.CENTER);
		usnum = new JLabel("최소 승차 인원수");
		usnum.setHorizontalAlignment(JLabel.CENTER);
		uscost = new JLabel("최대 하루 대여 비용");
		uscost.setHorizontalAlignment(JLabel.CENTER);
		urcampingcar = new JLabel("캠핑카");
		urcampingcar.setHorizontalAlignment(JLabel.CENTER);
		urselection = new JLabel("선택 및 대여");
		urselection.setHorizontalAlignment(JLabel.CENTER);
		urrentid = new JLabel("고유 대여 번호");
		urrentid.setHorizontalAlignment(JLabel.CENTER);
		urcarid = new JLabel("캠핑카 등록 ID");
		urcarid.setHorizontalAlignment(JLabel.CENTER);
		urcustid = new JLabel("운전면허증 번호");
		urcustid.setHorizontalAlignment(JLabel.CENTER);
		urrentdate = new JLabel("대여 날짜");
		urrentdate.setHorizontalAlignment(JLabel.CENTER);
		urterm = new JLabel("대여 기간");
		urterm.setHorizontalAlignment(JLabel.CENTER);

		usnumtf = new JTextField(10);
		uscosttf = new JTextField(10);
		urrentidtf = new JTextField(10);
		urcaridtf = new JTextField(10);
		urcustidtf = new JTextField(10);
		urrentdatetf = new JTextField(10);
		urtermtf = new JTextField(10);

		txtResult = new JTextArea();

		pn1 = new JPanel(new GridLayout(7, 8));
		pn1.add(uscampingcar);
		pn1.add(uselect);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(uscondition);
		pn1.add(usnum);
		pn1.add(uscost);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(usnumtf);
		pn1.add(uscosttf);
		pn1.add(userselect);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(urcampingcar);
		pn1.add(urselection);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(urrentid);
		pn1.add(urcarid);
		pn1.add(urcustid);
		pn1.add(urrentdate);
		pn1.add(urterm);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));
		pn1.add(urrentidtf);
		pn1.add(urcaridtf);
		pn1.add(urcustidtf);
		pn1.add(urrentdatetf);
		pn1.add(urtermtf);
		pn1.add(userrent);
		pn1.add(new JLabel(""));
		pn1.add(new JLabel(""));

		txtResult.setEditable(true);
		JScrollPane scrollPane = new JScrollPane(txtResult);

		add("North", pn1);
		add("Center", scrollPane);

		userselect.addActionListener(new DBActionListener());
		userrent.addActionListener(new DBActionListener());
	}
}